### ISSUE TITLE
window.event should be removed

### ISSUE THREAD

**Issue by zowers** [sindresorhus/globals#51]
`window.event` Microsoft-only so should be removed
https://developer.mozilla.org/en-US/docs/Web/API/Window/event

**Comment by kileras** [comment]
Hi,

I'm having a discussion about this specifically in the eslint repo, which if I'm not mistaken is using this repo in order to populate the globals. https://github.com/eslint/eslint/issues/3964

The fact is that the event is not a global variable in every context and in every browser, so for example in Firefox the global event variable will only be available in inline listeners like:
```
<body onclick="console.log(event)">
```
And the rest of the time it won't even exist. In other browsers like Chrome or IE (didn't test IE but both should work the same way) it will exist all the time but it will be undefined if the code is not in the context of an actual event. 

I think that the idea of this module is to have a comprehensive list of the generally available globals in all the browsers, the same way we don't include WebKitAnimationEvent as global despite being available in Chrome we shouldn't add event.

**Comment by sindresorhus** [comment]
Closing as this was declined in ESLint: https://github.com/eslint/eslint/issues/3964#issuecomment-146594802
